[tool.poetry]
name = "lambdaprecisionudggenerator"
version = "0.1.0"
description = ""
authors = ["foerster_work <foerster.work@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "<3.13,>=3.9"
numpy = "*"
matplotlib = "*"
joblib = "*"
networkx = "*"
scipy = "*"
pyomo = "*"
tikzplotlib = "*"
tabulate = "*"
gurobipy = "*"
pytest = "*"
pandas = "*"
distinctipy = "*"
pyqt6 = "*"
multiset = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
